### ISSUE TITLE
Upgrade to use AWS Java SDK v2

### ISSUE THREAD

**Issue by triggan** [aws/amazon-neptune-sigv4-signer#23]
The current version of the Amazon Neptune SigV4 Signer library leverages the AWS Java SDK v1.12.241.  We need to upgrade to the latest v2 version of the AWS Java SDK.

**Comment by aschwarte10** [comment]
@triggan in our product we are also migrating to the AWS Java SDK v2, and we have a dependency to the neptune sigv4 signer.

Could you maybe share some details on the timeline for this issue? This would help us to align the planning. 

Thanks

**Comment by deividferreira-hotmart** [comment]
I believe this pull request will resolve the issue I'm encountering. The removal of com.fasterxml.jackson.databind.PropertyNamingStrategy#PASCAL_CASE_TO_CAMEL_CASE poses challenges within AWS environments. This field is referenced by com.amazonaws.util.EC2MetadataUtils (a transitive reference in com.amazonaws:aws-java-sdk-core:jar:1.11.1009), and it triggers an error during Quarkus native compilation v3.9.5 (which employs Jackson 2.17.0).

Details error:
Error: Discovered unresolved field during parsing: com.fasterxml.jackson.databind.PropertyNamingStrategy.PASCAL_CASE_TO_CAMEL_CASE. This error is reported at image build time because class com.amazonaws.util.EC2MetadataUtils is registered for linking at image build time by command line and command line.
Error encountered while parsing com.amazonaws.util.EC2MetadataUtils.<clinit>(EC2MetadataUtils.java:81) 
Parsing context:
   at static root method.(Unknown Source)

**Comment by jetztgradnet** [comment]
@triggan Sorry for bugging you, but as we are planning to move to AWS SDK v2 due to the EOL for the v1 SDK, getting some hints regarding the timeline of this update would be really helpful.
Thanks!

**Comment by spmallette** [comment]
released in v3.0.0.
